version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: rv-classifieds-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: rv_classifieds
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - rv-network
    # Don't expose MongoDB port in production for security

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: rv-classifieds-backend
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://rvuser:${DB_PASSWORD:-rvpass123}@mongodb:27017/rv_classifieds
      - DB_NAME=rv_classifieds
    depends_on:
      - mongodb
    networks:
      - rv-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/stats"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: rv-classifieds-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    networks:
      - rv-network

  # Reverse proxy for production
  nginx-proxy:
    image: nginx:alpine
    container_name: rv-classifieds-proxy
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl:ro  # Mount SSL certificates if using HTTPS
    depends_on:
      - frontend
      - backend
    networks:
      - rv-network

volumes:
  mongodb_data:
    driver: local

networks:
  rv-network:
    driver: bridge
